/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Generics.maximum.problem;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
